-- 创建设置表
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_name TEXT DEFAULT '示例学校',
  max_students_per_class INTEGER DEFAULT 45,
  enable_notifications BOOLEAN DEFAULT true,
  auto_backup BOOLEAN DEFAULT true,
  backup_frequency TEXT DEFAULT 'daily',
  data_retention INTEGER DEFAULT 365,
  allow_student_registration BOOLEAN DEFAULT false,
  require_email_verification BOOLEAN DEFAULT true,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
